### ISSUE TITLE
Allow shorthands for report configuration

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#139]
Such as:
```yaml
reports:
  myreport:
    sort_by: uuid
```
or
```yaml
reports:
  myreport:
    columns:
      - id
      - description
```

**Comment by savchenko** [comment]
This looks like a part of the configuration in YAML. Could you explain where this will go / how it shall be used by an end-user?

**Comment by savchenko** [comment]
Are these parts of TC settings or reports are configured separately? Either way, this sounds like "pending working TOML".

Ping https://github.com/taskchampion/taskchampion/issues/164

**Comment by djmitche** [comment]
They're part of TC settings.

**Comment by djmitche** [comment]
In TOML (#164), this would change e.g.,

```toml
[report.garden]
filter = [
  "+garden"
]
```
to just
```toml
[report.garden]
filter = "+garden"
```

and
```toml
[report.garden]
sort = [ { sort_by = "description" } ]
```
to just
```toml
[report.garden]
sort = [ "description" ]
```
and on to
```toml
[report.garden]
sort = "description"
```

Generally:
 - everywhere we expect an array, allow a single element instead
 - everywhere we expect a table with only one required property, allow that property value instead

This is generally a user-convenience issue so not high priority at the moment, if that helps with triage.
