### ISSUE TITLE
Strip debug symbols in release

### ISSUE THREAD

**Issue by savchenko** [GothenburgBitFactory/taskchampion#208]
When building via `cargo build --release`, symbols are still present:
```
checksec --file=$HOME/.local/bin/ta
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH        Symbols         FORTIFY Fortified       Fortifiable     FILE
Full RELRO      Canary found      NX enabled    PIE enabled     No RPATH   No RUNPATH   19684) Symbols      No    0   12
```
Perhaps good ol' `RUSTFLAGS='-C link-arg=-s' cargo build --release` will do as default release step?

**Comment by djmitche** [comment]
Could this be accomplished in `Cargo.toml`?  https://doc.rust-lang.org/cargo/reference/profiles.html

Aside from binary size, what's the issue with including symbols?

**Comment by savchenko** [comment]
> Aside from binary size, what's the issue with including symbols?

None. But the difference is ~4.2 vs 17.3 Mb.

**Comment by savchenko** [comment]
> Could this be accomplished in Cargo.toml?

"It depends". This should eventually work:

```toml
cargo-features = ["strip"]

[workspace]
members = [
    "taskchampion",
    "cli",
    "sync-server"
]

[profile.release]
strip = "symbols"
```

At present this requires nightly rustc. With `rustc 1.48.0` that is shipped in Debian 11 the feature returns an error:
```
error: the option `Z` is only accepted on the nightly compiler
```
